package algomusic2021.seangoldie.jsyn.voices;

/**************
** WARNING - this code automatically generated by Syntona.
** The real source is probably a Syntona patch.
** Do NOT edit this file unless you copy it to another directory and change the name.
** Otherwise it is likely to get clobbered the next time you
** export Java source code from Syntona.
**
** Syntona is available from: http://www.softsynth.com/syntona/
*/

import com.jsyn.ports.UnitOutputPort;
import com.jsyn.unitgen.UnitVoice;
import com.jsyn.unitgen.SawtoothOscillator;
import com.jsyn.unitgen.VariableRateMonoReader;
import com.jsyn.ports.UnitInputPort;
import com.jsyn.unitgen.Multiply;
import com.softsynth.shared.time.TimeStamp;
import com.jsyn.unitgen.PassThrough;
import com.jsyn.unitgen.FilterLowPass;
import com.jsyn.data.SegmentedEnvelope;
import com.jsyn.unitgen.Circuit;

public class FilteredSawSingleOscVoice extends Circuit implements UnitVoice {
    // Declare units and ports.
    PassThrough mFrequencyPassThrough;
    public UnitInputPort frequency;
    PassThrough mAmplitudePassThrough;
    public UnitInputPort amplitude;
    PassThrough mOutputPassThrough;
    public UnitOutputPort output;
    PassThrough mFilterFreqPassThrough;
    public UnitInputPort filterFreq;
    PassThrough mFreqSpreadPassThrough;
    public UnitInputPort freqSpread;
    Multiply mAtimes;
    FilterLowPass mLowPass;
    SawtoothOscillator mSawOsc;
    SegmentedEnvelope mAmpFilterEnv;
    VariableRateMonoReader mMonoRdr;

    // Declare inner classes for any child circuits.

    public FilteredSawSingleOscVoice() {
        // Create unit generators.
        add(mFrequencyPassThrough = new PassThrough());
        addPort(frequency = mFrequencyPassThrough.input, "frequency");
        add(mAmplitudePassThrough = new PassThrough());
        addPort(amplitude = mAmplitudePassThrough.input, "amplitude");
        add(mOutputPassThrough = new PassThrough());
        addPort( output = mOutputPassThrough.output, "output");
        add(mFilterFreqPassThrough = new PassThrough());
        addPort(filterFreq = mFilterFreqPassThrough.input, "filterFreq");
        add(mFreqSpreadPassThrough = new PassThrough());
        addPort(freqSpread = mFreqSpreadPassThrough.input, "freqSpread");
        add(mAtimes = new Multiply());
        add(mLowPass = new FilterLowPass());
        add(mSawOsc = new SawtoothOscillator());
        double[] mAmpFilterEnvData = {
            1.3009759999686188, 1.0,
            0.9799220057385014, 0.5877192982456141,
            0.5582181969948603, 0.0,
        };
        mAmpFilterEnv = new SegmentedEnvelope( mAmpFilterEnvData );
        add(mMonoRdr = new VariableRateMonoReader());
        // Connect units and ports.
        mFrequencyPassThrough.output.connect(mAtimes.inputA);
        mFilterFreqPassThrough.output.connect(mLowPass.frequency);
        mFreqSpreadPassThrough.output.connect(mAtimes.inputB);
        mAtimes.output.connect(mSawOsc.frequency);
        mLowPass.output.connect(mOutputPassThrough.input);
        mSawOsc.output.connect(mLowPass.input);
        mMonoRdr.output.connect(mLowPass.amplitude);
        mMonoRdr.output.connect(mSawOsc.amplitude);
        // Setup
        frequency.setup(0.0, 391.99543598174927, 783.9908719634985);
        amplitude.setup(0.0, 0.5, 1.0);
        filterFreq.setup(40.0, 400.0, 6000.0);
        freqSpread.setup(1.0, 1.0, 3.0);
        mLowPass.Q.set(1.0);
        mMonoRdr.amplitude.set(1.0);
        mMonoRdr.rate.set(1.0);
    }

    public void noteOn(double frequency, double amplitude, TimeStamp timeStamp) {
        this.frequency.set(frequency, timeStamp);
        this.amplitude.set(amplitude, timeStamp);
        mMonoRdr.dataQueue.queueOn( mAmpFilterEnv, timeStamp);
    }

    public void noteOff(TimeStamp timeStamp) {
        mMonoRdr.dataQueue.queueOff( mAmpFilterEnv, false, timeStamp);
    }
    
    public UnitOutputPort getOutput() {
        return output;
    }
}
